<?php

$theme_shortname='bbse_commerce';

/**[SET] License**/
$varLcStatus=$theme_shortname."_".str_replace(" ","",strtolower(BBSE_THEME_NAME)).'_license_status';
$varLcKey=$theme_shortname."_".str_replace(" ","",strtolower(BBSE_THEME_NAME)).'_license_key';
$update_url = 'http://update.bbsetheme.com/update';

$bbseLanguageCodes=Array(
	"aa"=>"에티오피아" , // Afar
	"ab"=>"압하스어" , // Abkhazian
	"ae"=>"아베스타어" , // Avestan
	"af"=>"아프리카어" , // Afrikaans
	"ak"=>"아칸어" , // Akan
	"am"=>"암하라어" , // Amharic
	"an"=>"아라곤어" , // Aragonese
	"ar"=>"아라비아어" , // Arabic
	"as"=>"아삼어" , // Assamese
	"av"=>"아바르어" , // Avaric
	"ay"=>"아이마라어" , // Aymara
	"az"=>"아제르바이잔어" , // Azerbaijani
	"ba"=>"바스키르어" , // Bashkir
	"be"=>"벨라루스어" , // Belarusian
	"bg"=>"불가리아어" , // Bulgarian
	"bh"=>"비하르어" , // Bihari
	"bi"=>"비슐라마어" , // Bislama
	"bm"=>"밤바라어" , // Bambara
	"bn"=>"벵골어" , // Bengali
	"bo"=>"티베트어" , // Tibetan
	"br"=>"브르타뉴어" , // Breton
	"bs"=>"보스니아어" , // Bosnian
	"ca"=>"카탈로니아어" , // Catalan
	"ce"=>"체첸어" , // Chechen
	"ch"=>"차모로어" , // Chamorro
	"co"=>"코르시카어" , // Corsican
	"cr"=>"크리어" , // Cree
	"cs"=>"체코어" , // Czech
	"cu"=>"슬라브어" , // Church Slavic
	"cv"=>"추바슈어" , // Chuvash
	"cy"=>"웨일스어" , // Welsh
	"da"=>"덴마크어" , // Danish
	"de"=>"독일어" , // German
	"dv"=>"디베히어" , // Divehi
	"dz"=>"종카어" , // Dzongkha
	"ee"=>"가나어" , // Éwé
	"el"=>"그리스어" , // Greek
	"en"=>"영어" , // English
	"eo"=>"에스페란토" , // Esperanto
	"es"=>"스페인어" , // Spanish
	"et"=>"에스토니아어" , // Estonian
	"eu"=>"바스크어" , // Basque
	"fa"=>"페르시아어" , // Persian
	"ff"=>"풀라어" , // Fulah
	"fi"=>"핀란드어" , // Finnish
	"fj"=>"피지어" , // Fijian
	"fo"=>"페로어" , // Faroese
	"fr"=>"프랑스어" , // French
	"fy"=>"프리지아어" , // Western Frisian
	"ga"=>"아일랜드어" , // Irish
	"gd"=>"게일어" , // Scottish Gaelic
	"gl"=>"갈리시아어" , // Galician
	"gn"=>"과라니어" , // Guarani
	"gu"=>"구자라트어" , // Gujarati
	"gv"=>"맨섬어" , // Manx
	"ha"=>"하우사어" , // Hausa
	"he"=>"히브리어" , // Hebrew (formerly iw)
	"hi"=>"힌디어" , // Hindi
	"ho"=>"히리 모투어" , // Hiri Motu
	"hr"=>"크로아티아어" , // Croatian
	"ht"=>"아이티 크리올어" , // Haitian
	"hu"=>"헝가리어" , // Hungarian
	"hy"=>"아르메니아어" , // Armenian
	"hz"=>"헤레로어" , // Herero
	"ia"=>"국제어" , // Interlingua
	"id"=>"인도네시아어" , // Indonesian (formerly in)
	"ie"=>"인테르링구에어" , // Interlingue
	"ig"=>"이그보어" , // Igbo
	"ii"=>"쓰촨이어" , // Sichuan Yi
	"ik"=>"이누피아크어" , // Inupiak
	"io"=>"이도어" , // Ido
	"is"=>"아이슬란드어" , // Icelandic
	"it"=>"이탈리아어" , // Italian
	"iu"=>"이누이트어" , // Inuktitut
	"ja"=>"일본어" , // Japanese
	"jv"=>"자바어" , // Javanese
	"ka"=>"그루지야어" , // Georgian
	"kg"=>"콩고어" , // Kongo
	"ki"=>"키쿠유어" , // Kikuyu
	"kj"=>" 콰냐마어" , // Kuanyama
	"kk"=>"카자흐어" , // Kazakh
	"kl"=>"그린란드어" , // Kalaallisut
	"km"=>"크메르어" , // Central Khmer
	"kn"=>"칸나다어" , // Kannada
	"ko"=>"한국어" , // Korean
	"kr"=>"카누리어" , // Kanuri
	"ks"=>"카슈미르어" , // Kashmiri
	"ku"=>"쿠르드어" , // Kurdish
	"kv"=>"코미어" , // Komi
	"kw"=>"콘월어" , // Cornish
	"ky"=>"키르기즈어" , // Kirghiz
	"la"=>"라틴어" , // Latin
	"lb"=>"룩셈부르크어" , // Letzeburgesch
	"lg"=>"간다어" , // Ganda
	"li"=>"림뷔르흐어" , // Limburgish
	"ln"=>"링갈라어" , // Lingala
	"lo"=>"라오어" , // Lao
	"lt"=>"리투아니아어" , // Lithuanian
	"lu"=>"루바카탕가어" , // Luba-Katanga
	"lv"=>"라트비아어" , // Latvian
	"mg"=>"마다가스카르어" , // Malagasy
	"mh"=>"마셜어" , // Marshallese
	"mi"=>"마오리족어" , // Maori
	"mk"=>"마케도니아어" , // Macedonian
	"ml"=>"말라얄람어" , // Malayalam
	"mn"=>"몽고어" , // Mongolian
	"mo"=>"몰다비아어" , // Moldavian
	"mr"=>"마라타어" , // Marathi
	"ms"=>"말레이어" , // Malay
	"mt"=>"몰타어" , // Maltese
	"my"=>"버마어" , // Burmese
	"na"=>"나우루어" , // Nauru
	"nb"=>"노르웨이어(보크)" , // Norwegian Bokmål
	"nd"=>"북은데벨레어 " , // Ndebele, North
	"ne"=>"네팔어" , // Nepali
	"ng"=>"은동가어" , // Ndonga
	"nl"=>"네덜란드어" , // Dutch
	"nn"=>"노르웨이어(니노르스크)" , // Norwegian Nynorsk
	"no"=>"노르웨이어" , // Norwegian
	"nr"=>"은데벨레어" , // Ndebele, South
	"nv"=>"나바호어" , // Navajo
	"ny"=>"니안자어" , // Nyanja
	"oc"=>"오크어" , // Occitan
	"oj"=>"오지브와어" , // Ojibwa
	"om"=>"(아판)오로모어" , // (Afan) Oromo
	"or"=>"오리야어" , // Oriya
	"os"=>"오세트어" , // Ossetian
	"pa"=>"펀자브어" , // Panjabi
	"pi"=>"팔리어" , // Pali
	"pl"=>"폴란드어" , // Polish
	"ps"=>"파슈토어" , // Pashto
	"pt"=>"포르투갈어" , // Portuguese
	"qu"=>"케추아어" , // Quechua
	"rm"=>"레토로만어" , // Romansh
	"rn"=>"룬디어" , // Rundi
	"ro"=>"루마니아어" , // Romanian
	"ru"=>"러시아어" , // Russian
	"rw"=>"르완다어" , // Kinyarwanda
	"sa"=>"산스크리트어" , // Sanskrit
	"sc"=>"사르디니아어" , // Sardinian
	"sd"=>"신드어" , // Sindhi
	"se"=>"사미어" , // Northern Sami
	"sg"=>"상고어" , // Sango
	"si"=>"신할라어" , // Sinhala
	"sk"=>"슬로바키아어" , // Slovak
	"sl"=>"슬로베니아어" , // Slovenian
	"sm"=>"사모아어" , // Samoan
	"sn"=>"쇼나어" , // Shona
	"so"=>"소말리어" , // Somali
	"sq"=>"알바니아어" , // Albanian
	"sr"=>"세르비아어" , // Serbian
	"ss"=>"스와티어" , // Swati
	"st"=>"소토어" , // Sesotho
	"su"=>"순다어" , // Sundanese
	"sv"=>"스웨덴어" , // Swedish
	"sw"=>"스와힐리어" , // Swahili
	"ta"=>"타밀어" , // Tamil
	"te"=>"텔루구어" , // Telugu
	"tg"=>"타지크어" , // Tajik
	"th"=>"타이어" , // Thai
	"ti"=>"티그리냐어" , // Tigrinya
	"tk"=>"투르크멘어" , // Turkmen
	"tl"=>"타갈로그어" , // Tagalog
	"tn"=>"츠와나어" , // Tswana
	"to"=>"통가어" , // Tonga
	"tr"=>"터키어" , // Turkish
	"ts"=>"총가어" , // Tsonga
	"tt"=>"타타르어" , // Tatar
	"tw"=>"트위어" , // Twi
	"ty"=>"타히티어" , // Tahitian
	"ug"=>"위구르어" , // Uighur
	"uk"=>"우크라이나어" , // Ukrainian
	"ur"=>"우르두어" , // Urdu
	"uz"=>"우즈벡어" , // Uzbek
	"ve"=>"벤다어" , // Venda
	"vi"=>"베트남어" , // Vietnamese
	"vo"=>"볼라퓌크어" , // Volapük
	"wa"=>"왈론어" , // Walloon
	"wo"=>"월로프어" , // Wolof
	"xh"=>"Xhosa" , // Xhosa
	"yi"=>"이디시어" , // Yiddish (formerly ji)
	"yo"=>"요루바어" , // Yoruba
	"za"=>"좡어" , // Zhuang
	"zh"=>"중국어" , // Chinese
	"zu"=>"줄루어"  // Zulu
);

$options=array(
// [공통]  라이센스
	'license'=>
		array(
			array('name'=>'LICENSE',
					'type'=>'title'),
			array('name'=>'라이센스 상태',
					'id'=>$varLcStatus,
					'type'=>'text'),
			array('name'=>'라이센스 키',
					'id'=>$varLcKey,
					'type'=>'text')
		 ),

	'intro'=>
		array(
			array('name'=>'[공통] 테마 인트로 설정',
					'type'=>'title'),
			array('name'=>'[공통] 인트로 숨김설정',
					'id'=>$theme_shortname.'_intro_preOpen',
					'type'=>'text'),
			array('name'=>'[공통] 인트로 사용 여부',
					'id'=>$theme_shortname.'_intro_use',
					'type'=>'text'),
			array('name'=>'[공통] 인트로 종류',
					'id'=>$theme_shortname.'_intro_type',
					'type'=>'text'),
			array('name'=>'[공통] 인증수단',
					'id'=>$theme_shortname.'_intro_auth_kind',
					'type'=>'text'),
			array('name'=>'[공통] 인트로 로고',
					'id'=>$theme_shortname.'_intro_19_logo',
					'type'=>'text'),
			array('name'=>'[공통] 상단 배경색',
					'id'=>$theme_shortname.'_intro_19_color_top_background',
					'type'=>'text'),
			array('name'=>'[공통] 본문 배경색',
					'id'=>$theme_shortname.'_intro_19_color_middle_background',
					'type'=>'text'),
			array('name'=>'[공통] 본문 글자색',
					'id'=>$theme_shortname.'_intro_19_color_middle_foreground',
					'type'=>'text'),
			array('name'=>'[공통] 하단 배경색',
					'id'=>$theme_shortname.'_intro_19_color_bottom_background',
					'type'=>'text'),
			array('name'=>'[공통] 하단 글자색',
					'id'=>$theme_shortname.'_intro_19_color_bottom_foreground',
					'type'=>'text'),
			array('name'=>'[공통] 휴대폰인증 버튼 배경색',
					'id'=>$theme_shortname.'_intro_19_color_button_background',
					'type'=>'text'),
			array('name'=>'[공통] 휴대폰인증 버튼 글자색',
					'id'=>$theme_shortname.'_intro_19_color_button_foreground',
					'type'=>'text'),
			array('name'=>'[공통] 19세 미만 나가기 버튼 배경색',
					'id'=>$theme_shortname.'_intro_19_color_exitbutton_background',
					'type'=>'text'),
			array('name'=>'[공통] 19세 미만 나가기 버튼 글자색',
					'id'=>$theme_shortname.'_intro_19_color_exitbutton_foreground',
					'type'=>'text'),
			array('name'=>'[공통] 상단 배너',
					'id'=>$theme_shortname.'_intro_19_top_banner',
					'type'=>'text'),
			array('name'=>'[공통] 하단 인증마크 및 배너 사용여부',
					'id'=>$theme_shortname.'_intro_19_use_bottom_banner',
					'type'=>'hidden'),
			array('name'=>'[공통] 하단 인증마크 및 배너 정렬',
					'id'=>$theme_shortname.'_intro_19_bottom_banner_align',
					'type'=>'hidden'),
			array('name'=>'[공통] 19세 아이콘',
					'id'=>$theme_shortname.'_intro_19_icon',
					'type'=>'text'),
			array('name'=>'[공통] 아이콘 업로드',
					'id'=>$theme_shortname.'_intro_19_icon_img',
					'type'=>'text'),
			array('name'=>'[공통] 안내문구',
					'id'=>$theme_shortname.'_intro_19_introduce',
					'type'=>'text'),
			array('name'=>'[공통] 19세미만 나가기 사용여부',
					'id'=>$theme_shortname.'_intro_19_under_exit_use',
					'type'=>'text'),
			array('name'=>'[공통] 19세미만 나가기 이동 URL',
					'id'=>$theme_shortname.'_intro_19_under_exit_url',
					'type'=>'text'),
			array('name'=>'[공통] 푸터 내용',
					'id'=>$theme_shortname.'_intro_19_footer',
					'type'=>'text'),
			array('name'=>'[공통] 회원로그인 사용여부',
					'id'=>$theme_shortname.'_intro_19_login_use',
					'type'=>'text'),
			array('name'=>'[공통] 서브페이지 접근 차단',
					'id'=>$theme_shortname.'_intro_19_subpage_blocking_use',
					'type'=>'text'),
			array('name'=>'[공통] 서브페이지 접근 차단 체크',
					'id'=>$theme_shortname.'_intro_19_subpage_blocking_check',
					'type'=>'text'),
			array('name'=>'[공통] 인트로 생략 Referer URL',
					'id'=>$theme_shortname.'_intro_19_jump_url',
					'type'=>'text'),
		),

	'layout'=>
		array(
			array('name'=>'레이아웃 설정',
					'type'=>'title'),
			array('name'=>'레이아웃 설정 숨김설정',
					'id'=>$theme_shortname.'_layout_preOpen',
					'type'=>'hidden'),
			array('name'=>'왼쪽 쇼핑 카테고리 리스트',
					'id'=>$theme_shortname.'_layout_left_category',
					'type'=>'radio'),
			array('name'=>'왼쪽 쇼핑 카테고리 bold',
					'id'=>$theme_shortname.'_layout_left_category_bold',
					'type'=>'radio'),
			array('name'=>'가격검색',
					'id'=>$theme_shortname.'_layout_left_price_search',
					'type'=>'radio'),
			array('name'=>'오늘만의 특가',
					'id'=>$theme_shortname.'_layout_left_today_sale',
					'type'=>'radio'),
			array('name'=>'핫아이템',
					'id'=>$theme_shortname.'_layout_left_hot_item',
					'type'=>'radio'),
			array('name'=>'입금계좌정보',
					'id'=>$theme_shortname.'_layout_left_bank_info',
					'type'=>'radio'),
			array('name'=>'최근 본 상품',
					'id'=>$theme_shortname.'_layout_right_last_goods',
					'type'=>'radio'),
			
			array('name'=>'[공통] 관리자화면 로고',
				'id'=>$theme_shortname.'_wpadmin_logo_img',
				'type'=>'text'),
			array('name'=>'[공통] 관리자화면 텍스트문구',
				'id'=>$theme_shortname.'_wpadmin_txt',
				'type'=>'text'),
			array('name'=>'[공통] 관리자화면 배경색',
				'id'=>$theme_shortname.'_wpadmin_bg',
				'type'=>'text'),
		),

	'basic'=>
		array(
			array('name'=>'상단 배너 사용여부',
					'id'=>$theme_shortname.'_sub_use_top_banner',
					'type'=>'radio'),
		  array('name'=>'상단 배너 이미지',
					'id'=>$theme_shortname.'_sub_top_banner_image_1',
					'type'=>'text'),
		  array('name'=>'상단 배너 링크',
					'id'=>$theme_shortname.'_sub_top_banner_link_1',
					'type'=>'text'),
		  array('name'=>'상단 배너 링크 창',
					'id'=>$theme_shortname.'_sub_top_banner_link_1_window',
					'type'=>'text'),
			array('name'=>'기본 설정',
				'type'=>'title'),
			array('name'=>'기본 설정 숨김설정',
					'id'=>$theme_shortname.'_basic_preOpen',
					'type'=>'hidden'),
			array('name'=>'언어사이트설정 사용여부',
				'id'=>$theme_shortname.'_basic_hreflang_use',
				'type'=>'radio'),
			array('name'=>'언어사이트설정',
				'id'=>$theme_shortname.'_basic_hreflang',
				'type'=>'radio'),
			array('name'=>'로고 설정(상단)',
				'id'=>$theme_shortname.'_basic_logo_type_top',
				'type'=>'radio'),
			array('name'=>'텍스트 타이틀',
				'id'=>$theme_shortname.'_basic_logo_text_top',
				'type'=>'text'),
			array('name'=>'텍스트 글꼴 색상',
				'id'=>$theme_shortname.'_basic_logo_color_top',
				'type'=>'colpick'),
			array('name'=>'텍스트 글꼴 크기',
				'id'=>$theme_shortname.'_basic_logo_text_size_top',
				'type'=>'text'),
			array('name'=>'이미지 로고',
				'id'=>$theme_shortname.'_basic_logo_img_top',
				'type'=>'upload'),
			array('name'=>'로고 위치(top)',
				'id'=>$theme_shortname.'_basic_logo_top_margin',
				'type'=>'text'),
			array('name'=>'로고 설정(하단)',
				'id'=>$theme_shortname.'_basic_logo_type_bottom',
				'type'=>'radio'),
			array('name'=>'텍스트 타이틀',
				'id'=>$theme_shortname.'_basic_logo_text_bottom',
				'type'=>'text'),
			array('name'=>'텍스트 글꼴 색상',
				'id'=>$theme_shortname.'_basic_logo_color_bottom',
				'type'=>'colpick'),
			array('name'=>'텍스트 글꼴 크기',
				'id'=>$theme_shortname.'_basic_logo_text_size_bottom',
				'type'=>'text'),
			array('name'=>'이미지 로고',
				'id'=>$theme_shortname.'_basic_logo_img_bottom',
				'type'=>'upload'),
			array('name'=>'파비콘',
				'id'=>$theme_shortname.'_basic_favorit_icon',
				'type'=>'upload'),
			array('name'=>'메인 슬라이드 사용여부 1',
				'id'=>$theme_shortname.'_basic_main_slide_use_1',
				'type'=>'text'),
			array('name'=>'메인 슬라이드 타이틀 1',
				'id'=>$theme_shortname.'_basic_main_slide_excerpt_1',
				'type'=>'text'),
			array('name'=>'메인 슬라이드 이미지 1',
				'id'=>$theme_shortname.'_basic_main_slide_img_1',
				'type'=>'upload'),
			array('name'=>'메인 슬라이드 타이틀 링크 1',
				'id'=>$theme_shortname.'_basic_main_slide_url_1',
				'type'=>'text'),
			array('name'=>'메인 슬라이드 타이틀 링크 창 1',
				'id'=>$theme_shortname.'_basic_main_slide_url_1_window',
				'type'=>'text'),
			array('name'=>'메인 슬라이드 사용여부 2',
				'id'=>$theme_shortname.'_basic_main_slide_use_2',
				'type'=>'text'),
			array('name'=>'메인 슬라이드 타이틀 2',
				'id'=>$theme_shortname.'_basic_main_slide_excerpt_2',
				'type'=>'text'),
			array('name'=>'메인 슬라이드 이미지 2',
				'id'=>$theme_shortname.'_basic_main_slide_img_2',
				'type'=>'upload'),
			array('name'=>'메인 슬라이드 타이틀 링크 2',
				'id'=>$theme_shortname.'_basic_main_slide_url_2',
				'type'=>'text'),
			array('name'=>'메인 슬라이드 타이틀 링크 창 2',
				'id'=>$theme_shortname.'_basic_main_slide_url_2_window',
				'type'=>'text'),
			array('name'=>'메인 슬라이드 사용여부 3',
				'id'=>$theme_shortname.'_basic_main_slide_use_3',
				'type'=>'text'),
			array('name'=>'메인 슬라이드 타이틀 3',
				'id'=>$theme_shortname.'_basic_main_slide_excerpt_3',
				'type'=>'text'),
			array('name'=>'메인 슬라이드 이미지 3',
				'id'=>$theme_shortname.'_basic_main_slide_img_3',
				'type'=>'upload'),
			array('name'=>'메인 슬라이드 타이틀 링크 3',
				'id'=>$theme_shortname.'_basic_main_slide_url_3',
				'type'=>'text'),
			array('name'=>'메인 슬라이드 타이틀 링크 창 3',
				'id'=>$theme_shortname.'_basic_main_slide_url_3_window',
				'type'=>'text'),
			array('name'=>'하단 퀵링크 타이틀1',
				'id'=>$theme_shortname.'_basic_footer_quick_link_1',
				'type'=>'text'),
			array('name'=>'하단 퀵링크 URL1',
				'id'=>$theme_shortname.'_basic_footer_quick_link_1_url',
				'type'=>'text'),
			array('name'=>'하단 퀵링크 TARGET1',
				'id'=>$theme_shortname.'_basic_footer_quick_link_1_window',
				'type'=>'radio'),
			array('name'=>'하단 퀵링크 타이틀2',
				'id'=>$theme_shortname.'_basic_footer_quick_link_2',
				'type'=>'text'),
			array('name'=>'하단 퀵링크 URL2',
				'id'=>$theme_shortname.'_basic_footer_quick_link_2_url',
				'type'=>'text'),
			array('name'=>'하단 퀵링크 TARGET2',
				'id'=>$theme_shortname.'_basic_footer_quick_link_2_window',
				'type'=>'radio'),
			array('name'=>'하단 퀵링크 타이틀3',
				'id'=>$theme_shortname.'_basic_footer_quick_link_3',
				'type'=>'text'),
			array('name'=>'하단 퀵링크 URL3',
				'id'=>$theme_shortname.'_basic_footer_quick_link_3_url',
				'type'=>'text'),
			array('name'=>'하단 퀵링크 TARGET3',
				'id'=>$theme_shortname.'_basic_footer_quick_link_3_window',
				'type'=>'radio'),
			array('name'=>'하단 퀵링크 타이틀4',
				'id'=>$theme_shortname.'_basic_footer_quick_link_4',
				'type'=>'text'),
			array('name'=>'하단 퀵링크 URL4',
				'id'=>$theme_shortname.'_basic_footer_quick_link_4_url',
				'type'=>'text'),
			array('name'=>'하단 퀵링크 TARGET4',
				'id'=>$theme_shortname.'_basic_footer_quick_link_4_window',
				'type'=>'radio'),
			array('name'=>'하단 퀵링크 타이틀5',
				'id'=>$theme_shortname.'_basic_footer_quick_link_5',
				'type'=>'text'),
			array('name'=>'하단 퀵링크 URL5',
				'id'=>$theme_shortname.'_basic_footer_quick_link_5_url',
				'type'=>'text'),
			array('name'=>'하단 퀵링크 TARGET5',
				'id'=>$theme_shortname.'_basic_footer_quick_link_5_window',
				'type'=>'radio'),
			array('name'=>'관계사 사이트 사용여부',
				'id'=>$theme_shortname.'_basic_use_footer_family_site',
				'type'=>'hidden'),
			array('name'=>'하단 사이트 정보',
				'id'=>$theme_shortname.'_basic_footer',
				'type'=>'text'),
			array('name'=>'하단 사이트 저작권 정보',
				'id'=>$theme_shortname.'_basic_footer_copyright',
				'type'=>'text'),
			array('name'=>'인증마크 및 하단배너 사용여부',
				'id'=>$theme_shortname.'_basic_use_bottom_banner',
				'type'=>'hidden')
	   ),

	'display'=>
		array(
			array('name'=>'디스플레이 설정',
				'type'=>'title'),
			array('name'=>'디스플레이 설정 숨김설정',
					'id'=>$theme_shortname.'_display_preOpen',
					'type'=>'hidden'),

			array('name'=>'모바일 아이콘 사용 여부',
				'id'=>$theme_shortname.'_display_use_mobile_icon',
				'type'=>'text'),
			array('name'=>'모바일 아이콘 메뉴 위치',
				'id'=>$theme_shortname.'_display_use_mobile_icon_position',
				'type'=>'text'),
			array('name'=>'모바일 아이콘 메뉴 배경색',
				'id'=>$theme_shortname.'_display_mobile_icon_menu_bgcolor',
				'type'=>'text'),
			array('name'=>'모바일 아이콘 메뉴 글자색',
				'id'=>$theme_shortname.'_display_mobile_icon_menu_color',
				'type'=>'text'),
			array('name'=>'모바일 아이콘 구분선 사용 여부',
				'id'=>$theme_shortname.'_display_use_mobile_icon_line',
				'type'=>'text'),
			array('name'=>'모바일 아이콘 구분선 종류',
				'id'=>$theme_shortname.'_display_mobile_icon_line_type',
				'type'=>'text'),
			array('name'=>'모바일 아이콘 구분선 색',
				'id'=>$theme_shortname.'_display_mobile_icon_line_color',
				'type'=>'text'),
			array('name'=>'모바일 아이콘 배경 사용 여부',
				'id'=>$theme_shortname.'_display_use_mobile_icon_bgcolor',
				'type'=>'text'),
			array('name'=>'모바일 아이콘색',
				'id'=>$theme_shortname.'_display_mobile_icon_color',
				'type'=>'text'),
			array('name'=>'모바일 아이콘 배경색',
				'id'=>$theme_shortname.'_display_mobile_icon_bgcolor',
				'type'=>'text'),
			array('name'=>'모바일 아이콘 그림자 효과 사용 여부',
				'id'=>$theme_shortname.'_display_use_mobile_icon_shadow',
				'type'=>'text'),
			array('name'=>'모바일 아이콘 그림자 색',
				'id'=>$theme_shortname.'_display_mobile_icon_shadow_color',
				'type'=>'text'),
			array('name'=>'모바일 아이콘 그림자 투명도',
				'id'=>$theme_shortname.'_display_mobile_icon_shadow_alpha',
				'type'=>'text'),

			array('name'=>'메인화면 중간배너 사용여부',
				'id'=>$theme_shortname.'_display_use_middle_banner',
				'type'=>'hidden'),
			array('name'=>'메인 중간배너 이미지1',
				'id'=>$theme_shortname.'_display_middle_banner_image_1',
				'type'=>'text'),
			array('name'=>'메인 중간배너 링크1',
				'id'=>$theme_shortname.'_display_middle_banner_link_1',
				'type'=>'text'),
			array('name'=>'메인 중간배너 링크1 타켓',
				'id'=>$theme_shortname.'_display_middle_banner_link_1_window',
				'type'=>'radio'),
			array('name'=>'메인 중간배너 이미지2',
				'id'=>$theme_shortname.'_display_middle_banner_image_2',
				'type'=>'text'),
			array('name'=>'메인 중간배너 링크2',
				'id'=>$theme_shortname.'_display_middle_banner_link_2',
				'type'=>'text'),
			array('name'=>'메인 중간배너 링크2 타켓',
				'id'=>$theme_shortname.'_display_middle_banner_link_2_window',
				'type'=>'radio'),
			array('name'=>'메인화면 하단배너 사용여부',
				'id'=>$theme_shortname.'_display_use_bottom_banner',
				'type'=>'hidden'),
			array('name'=>'메인화면 하단배너 이미지1',
				'id'=>$theme_shortname.'_display_bottom_banner_image_1',
				'type'=>'text'),
			array('name'=>'메인화면 하단배너 링크1',
				'id'=>$theme_shortname.'_display_bottom_banner_link_1',
				'type'=>'text'),
			array('name'=>'메인화면 하단배너 링크1 타켓',
				'id'=>$theme_shortname.'_display_bottom_banner_link_1_window',
				'type'=>'radio'),
			array('name'=>'왼쪽 배너 사용여부',
				'id'=>$theme_shortname.'_display_use_left_banner',
				'type'=>'hidden'),
			array('name'=>'왼쪽 롤링배너 사용여부',
				'id'=>$theme_shortname.'_display_use_left_rolling_banner',
				'type'=>'radio'),
			array('name'=>'오른쪽 배너 사용여부',
				'id'=>$theme_shortname.'_display_use_right_banner',
				'type'=>'hidden'),
			array('name'=>'오른쪽 롤링배너 사용여부',
				'id'=>$theme_shortname.'_display_use_right_rolling_banner',
				'type'=>'radio'),
			array('name'=>'C/S CENTER 사용여부',
				'id'=>$theme_shortname.'_display_use_cs_center',
				'type'=>'hidden'),
			array('name'=>'게시판 설정 적용타입',
				'id'=>$theme_shortname.'_display_cs_center_board_type',
				'type'=>'radio'),
			array('name'=>'게시판 설정 타이틀',
				'id'=>$theme_shortname.'_display_cs_center_board_title',
				'type'=>'text'),
			array('name'=>'게시판 설정 적용내용',
				'id'=>$theme_shortname.'_display_cs_center_board_content',
				'type'=>'radio'),
			array('name'=>'게시판 적용페이지',
				'id'=>$theme_shortname.'_display_cs_center_board_page',
				'type'=>'select'),
			array('name'=>'C/S CENTER 설정 타이틀',
				'id'=>$theme_shortname.'_display_cs_center_title',
				'type'=>'text'),
			array('name'=>'C/S CENTER 설정 전화번호',
				'id'=>$theme_shortname.'_display_cs_center_phone',
				'type'=>'text'),
			array('name'=>'C/S CENTER 설정 내용',
				'id'=>$theme_shortname.'_display_cs_center_content',
				'type'=>'text'),
		),

	'goodsplace'=>
		array(
			array('name'=>'상품배치 설정',
				'type'=>'title'),
			array('name'=>'상품배치 설정 숨김설정',
					'id'=>$theme_shortname.'_goodsplace_preOpen',
					'type'=>'hidden'),
			array('name'=>'추천상품 배치순위',
				'id'=>$theme_shortname.'_goodsplace_sort_1',
				'type'=>'select'),
			array('name'=>'추천상품 사용여부',
				'id'=>$theme_shortname.'_goodsplace_use_1',
				'type'=>'radio'),
			array('name'=>'추천상품 명칭변경',
				'id'=>$theme_shortname.'_goodsplace_title_1',
				'type'=>'text'),
			array('name'=>'추천상품 부가설명',
				'id'=>$theme_shortname.'_goodsplace_description_1',
				'type'=>'text'),
			array('name'=>'추천상품 더보기 링크',
				'id'=>$theme_shortname.'_goodsplace_url_1',
				'type'=>'text'),
			array('name'=>'추천상품 더보기 타켓',
				'id'=>$theme_shortname.'_goodsplace_url_1_window',
				'type'=>'radio'),
			array('name'=>'베스트상품 배치순위',
				'id'=>$theme_shortname.'_goodsplace_sort_2',
				'type'=>'select'),
			array('name'=>'베스트상품 사용여부',
				'id'=>$theme_shortname.'_goodsplace_use_2',
				'type'=>'radio'),
			array('name'=>'베스트상품 명칭변경',
				'id'=>$theme_shortname.'_goodsplace_title_2',
				'type'=>'text'),
			array('name'=>'베스트상품 부가설명',
				'id'=>$theme_shortname.'_goodsplace_description_2',
				'type'=>'text'),
			array('name'=>'베스트상품 더보기 링크',
				'id'=>$theme_shortname.'_goodsplace_url_2',
				'type'=>'text'),
			array('name'=>'베스트상품 더보기 타켓',
				'id'=>$theme_shortname.'_goodsplace_url_2_window',
				'type'=>'radio'),
			array('name'=>'MD기획상품 배치순위',
				'id'=>$theme_shortname.'_goodsplace_sort_3',
				'type'=>'select'),
			array('name'=>'MD기획상품 사용여부',
				'id'=>$theme_shortname.'_goodsplace_use_3',
				'type'=>'radio'),
			array('name'=>'MD기획상품 명칭변경',
				'id'=>$theme_shortname.'_goodsplace_title_3',
				'type'=>'text'),
			array('name'=>'MD기획상품 부가설명',
				'id'=>$theme_shortname.'_goodsplace_description_3',
				'type'=>'text'),
			array('name'=>'MD기획상품 표시개수',
				'id'=>$theme_shortname.'_goodsplace_line_3',
				'type'=>'radio'),
			array('name'=>'신상품 배치순위',
				'id'=>$theme_shortname.'_goodsplace_sort_4',
				'type'=>'select'),
			array('name'=>'신상품 사용여부',
				'id'=>$theme_shortname.'_goodsplace_use_4',
				'type'=>'radio'),
			array('name'=>'신상품 명칭변경',
				'id'=>$theme_shortname.'_goodsplace_title_4',
				'type'=>'text'),
			array('name'=>'신상품 부가설명',
				'id'=>$theme_shortname.'_goodsplace_description_4',
				'type'=>'text'),
			array('name'=>'베스트 상품평 배치순위',
				'id'=>$theme_shortname.'_goodsplace_sort_5',
				'type'=>'select'),
			array('name'=>'베스트 상품평 사용여부',
				'id'=>$theme_shortname.'_goodsplace_use_5',
				'type'=>'radio'),
			array('name'=>'베스트 상품평 명칭변경',
				'id'=>$theme_shortname.'_goodsplace_title_5',
				'type'=>'text'),
			array('name'=>'베스트 상품평 부가설명',
				'id'=>$theme_shortname.'_goodsplace_description_5',
				'type'=>'text'),
			array('name'=>'베스트 상품평 표시개수',
				'id'=>$theme_shortname.'_goodsplace_line_5',
				'type'=>'radio'),
			array('name'=>'베스트 상품평 더보기 링크',
				'id'=>$theme_shortname.'_goodsplace_url_5',
				'type'=>'text'),
			array('name'=>'베스트 상품평 더보기 타켓',
				'id'=>$theme_shortname.'_goodsplace_url_5_window',
				'type'=>'radio')
		),
	'shopsidebar'=>
		array(
			array('name'=>'[쇼핑몰] 사이드바 설정',
				'type'=>'title'),
			array('name'=>'[쇼핑몰] 우측사이드바 숨김설정',
				'id'=>$theme_shortname.'_shopsidebar_preOpen',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 상단 이벤트 배너 사용여부',
				'id'=>$theme_shortname.'_shopsidebar_top_banner',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 상단 이벤트 배너 이미지1',
				'id'=>$theme_shortname.'_shopsidebar_top_banner_img_1',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 상단 이벤트 배너 링크1',
				'id'=>$theme_shortname.'_shopsidebar_top_banner_url_1',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 상단 이벤트 배너 창1',
				'id'=>$theme_shortname.'_shopsidebar_top_banner_url_1_window',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 상단 이벤트 배너 이미지2',
				'id'=>$theme_shortname.'_shopsidebar_top_banner_img_2',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 상단 이벤트 배너 링크2',
				'id'=>$theme_shortname.'_shopsidebar_top_banner_url_2',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 상단 이벤트 배너 창2',
				'id'=>$theme_shortname.'_shopsidebar_top_banner_url_2_window',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 상단 이벤트 배너 이미지3',
				'id'=>$theme_shortname.'_shopsidebar_top_banner_img_3',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 상단 이벤트 배너 링크3',
				'id'=>$theme_shortname.'_shopsidebar_top_banner_url_3',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 상단 이벤트 배너 창3',
				'id'=>$theme_shortname.'_shopsidebar_top_banner_url_3_window',
				'type'=>'text'),
			
			array('name'=>'[쇼핑몰] 퀵메뉴 사용여부',
				'id'=>$theme_shortname.'_shopsidebar_use_quick_menu',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 아이콘1',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_img_1',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 메뉴명1',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_text_1',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 링크1',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_url_1',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 창1',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_url_1_window',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 아이콘2',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_img_2',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 메뉴명2',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_text_2',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 링크2',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_url_2',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 창2',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_url_2_window',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 아이콘3',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_img_3',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 메뉴명3',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_text_3',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 링크3',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_url_3',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 창3',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_url_3_window',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 아이콘4',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_img_4',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 메뉴명4',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_text_4',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 링크4',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_url_4',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 창4',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_url_4_window',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 아이콘5',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_img_5',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 메뉴명5',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_text_5',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 링크5',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_url_5',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 창5',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_url_5_window',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 아이콘6',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_img_6',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 메뉴명6',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_text_6',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 링크6',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_url_6',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] 퀵메뉴 창6',
				'id'=>$theme_shortname.'_shopsidebar_quick_menu_url_6_window',
				'type'=>'text'),
				
			array('name'=>'[쇼핑몰] SNS링크 사용여부',
				'id'=>$theme_shortname.'_shopsidebar_use_sns_menu',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] SNS링크 페이스북',
				'id'=>$theme_shortname.'_shopsidebar_sns_facebook',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] SNS링크 인스타그램',
				'id'=>$theme_shortname.'_shopsidebar_sns_insta',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] SNS링크 카카오톡',
				'id'=>$theme_shortname.'_shopsidebar_sns_kakao',
				'type'=>'text'),
			array('name'=>'[쇼핑몰] SNS링크 네이버톡',
				'id'=>$theme_shortname.'_shopsidebar_sns_naver',
				'type'=>'text'),
		),
	'sub'=>
		array(
			array('name'=>'서브화면 설정',
					'type'=>'title'),
			array('name'=>'서브화면 설정 숨김설정',
					'id'=>$theme_shortname.'_sub_preOpen',
					'type'=>'hidden'),
			array('name'=>'스킨',
					'id'=>$theme_shortname.'_sub_skin_name',
					'type'=>'select'),
			array('name'=>'좌측 사이드바 사용여부',
					'id'=>$theme_shortname.'_sub_goods_view_use_left_sidebar',
					'type'=>'radio'),
			array('name'=>'주색',
					'id'=>$theme_shortname.'_sub_skin_color',
					'type'=>'colpick'),
		  array('name'=>'카테고리 배너 사용여부',
					'id'=>$theme_shortname.'_sub_use_category_banner',
					'type'=>'radio'),
		  array('name'=>'카테고리 배너 이미지',
					'id'=>$theme_shortname.'_sub_category_banner_image_1',
					'type'=>'text'),
		  array('name'=>'카테고리 배너 링크',
					'id'=>$theme_shortname.'_sub_category_banner_link_1',
					'type'=>'text'),
		  array('name'=>'카테고리 배너 링크 창',
					'id'=>$theme_shortname.'_sub_category_banner_link_1_window',
					'type'=>'text'),
		
		  array('name'=>'일반(리스트) 카테고리',
					'id'=>$theme_shortname.'_sub_category_view_list',
					'type'=>'text'),
		  array('name'=>'갤러리 카테고리',
					'id'=>$theme_shortname.'_sub_category_view_gallery',
					'type'=>'text'),
			array('name'=>'코멘트 활성화 페이지',
					'id'=>$theme_shortname.'_sub_comment_enable_page',
					'type'=>'text'),
			array("name"=>"사용여부",
					"id"=>$theme_shortname."_goodsrelation_use",
					"type"=>""),
			array('name'=>'구글 맞춤검색 사용여부',
				'id'=>$theme_shortname.'_sub_google_cse_use',
				'type'=>'text'),

			array('name'=>'구글 맞춤검색 글(포스트) 사용여부',
				'id'=>$theme_shortname.'_sub_google_cse_postUse',
				'type'=>'text'),
			array('name'=>'구글 맞춤검색 상품상세 사용여부',
				'id'=>$theme_shortname.'_sub_google_cse_goodsUse',
				'type'=>'text'),
			array('name'=>'구글 맞춤검색 코드',
				'id'=>$theme_shortname.'_sub_google_cse_code',
				'type'=>'text'),
			array('name'=>'구글 맞춤검색 바 정렬위치',
				'id'=>$theme_shortname.'_sub_google_cse_align',
				'type'=>'text'),
		),

	'color'=>
		array(
			array('name'=>'색(Color) 설정',
					'type'=>'title'),
			array('name'=>'색(Color) 설정 숨김설정',
					'id'=>$theme_shortname.'_color_preOpen',
					'type'=>'hidden'),
			array('name'=>'기본 색상',
					'id'=>$theme_shortname.'_color_main_theme',
					'type'=>'colpick'),
			array('name'=>'사이드바 배경색',
					'id'=>$theme_shortname.'_color_sidebar_background',
					'type'=>'colpick'),
			array('name'=>'사이드바 타이틀',
					'id'=>$theme_shortname.'_color_sidebar_title',
					'type'=>'colpick'),
					
			array('name'=>'메인메뉴바 배경색',
					'id'=>$theme_shortname.'_color_mainmenu_bg',
					'type'=>'colpick'),
			array('name'=>'메인메뉴 폰트 색상',
					'id'=>$theme_shortname.'_color_mainmenu_font',
					'type'=>'colpick'),
			array('name'=>'메인메뉴 폰트 크기',
					'id'=>$theme_shortname.'_color_mainmenu_font_size',
					'type'=>'title'),
		),

	'member'=>
		array(
			array('name'=>'회원가입/약관/방침',
					'type'=>'title'),
			array('name'=>'회원가입/약관/방침 숨김설정',
					'id'=>$theme_shortname.'_member_preOpen',
					'type'=>'hidden'),
			array('name'=>'이용약관',
					'id'=>$theme_shortname.'_member_agreement',
					'type'=>'textarea'),
			array('name'=>'개인정보취급방침',
					'id'=>$theme_shortname.'_member_private_1',
					'type'=>'textarea'),
			array('name'=>'이메일 무단수집 거부',
					'id'=>$theme_shortname.'_member_email_reject',
					'type'=>'textarea'),
			array('name'=>'전자금융거래 회원가입 시 화면표시 여부',
					'id'=>$theme_shortname.'_member_agreement_order_view_yn',
					'type'=>'radio'),
			array('name'=>'전자금융거래 비회원구매 시 화면표시 여부',
					'id'=>$theme_shortname.'_member_agreement_nonmember_view_yn',
					'type'=>'radio'),
			array('name'=>'전자금융거래 이용약관',
					'id'=>$theme_shortname.'_member_agreement_order',
					'type'=>'textarea'),
			array('name'=>'개인정보 수집 및 이용에 대한 안내',
					'id'=>$theme_shortname.'_member_private_2',
					'type'=>'textarea'),
			array('name'=>'회원탈퇴 약관',
					'id'=>$theme_shortname.'_member_agreement_leave',
					'type'=>'textarea')
		),

	'memberpage'=>
		array(
			array('name'=>'회원가입/약관/방침 페이지',
					'type'=>'title'),
			array('name'=>'회원가입/약관/방침 페이지 숨김설정',
					'id'=>$theme_shortname.'_memberpage_preOpen',
					'type'=>'hidden'),
			array('name'=>'이용약관',
					'id'=>$theme_shortname.'_memberpage_agreement',
					'type'=>'textarea'),
			array('name'=>'개인정보취급방침',
					'id'=>$theme_shortname.'_memberpage_private_1',
					'type'=>'textarea'),
			array('name'=>'전자금융거래 이용약관',
					'id'=>$theme_shortname.'_memberpage_agreement_order',
					'type'=>'textarea'),
			array('name'=>'회원탈퇴 약관',
					'id'=>$theme_shortname.'_memberpage_agreement_leave',
					'type'=>'textarea')
		),

	'ssl'=>
		array(
			array('name'=>'SSL(보안서버)',
					'type'=>'title'),
			array('name'=>'SSL(보안서버)',
					'id'=>$theme_shortname.'_ssl_preOpen',
					'type'=>'hidden'),
			array('name'=>'SSL 사용여부',
					'id'=>$theme_shortname.'_ssl_enable',
					'type'=>'radio'),
			array('name'=>'SSL 도메인',
					'id'=>$theme_shortname.'_ssl_domain',
					'type'=>'text'),
			array('name'=>'SSL 포트번호',
					'id'=>$theme_shortname.'_ssl_port',
					'type'=>'text')
		),

	'sns'=>
		array(
			array('name'=>'SNS',
					'type'=>'title'),
			array('name'=>'SNS 숨김설정',
					'id'=>$theme_shortname.'_sns_preOpen',
					'type'=>'hidden'),
			array('name'=>'트위터 포스트 공유 사용 여부',
					'id'=>$theme_shortname.'_sns_share_twitter',
					'type'=>'text'),
			array('name'=>'페이스북 포스트 공유 사용 여부',
					'id'=>$theme_shortname.'_sns_share_facebook',
					'type'=>'text'),
			array('name'=>'네이버 블로그 공유 사용 여부',
					'id'=>$theme_shortname.'_sns_share_naver',
					'type'=>'text'),
			array('name'=>'HMS 포스트 공유 사용 여부',
					'id'=>$theme_shortname.'_sns_share_hms',
					'type'=>'text'),
			array('name'=>'카카오톡 공유 사용 여부',
					'id'=>$theme_shortname.'_sns_share_kTalk',
					'type'=>'text'),
			array('name'=>'카카오스토리 공유 사용 여부',
					'id'=>$theme_shortname.'_sns_share_kStory',
					'type'=>'text'),
			array('name'=>'구글플러스 공유 사용 여부',
					'id'=>$theme_shortname.'_sns_share_googleplus',
					'type'=>'text'),
			array('name'=>'핀터레스트 공유 사용 여부',
					'id'=>$theme_shortname.'_sns_share_pinterest',
					'type'=>'text'),
			array('name'=>'하단영역에 SNS 아이콘 노출(트위터)',
					'id'=>$theme_shortname.'_sns_twitter_enable',
					'type'=>'radio'),
			array('name'=>'하단영역에 SNS 아이콘 노출(트위터)',
					'id'=>$theme_shortname.'_sns_twitter_url',
					'type'=>'text'),
			array('name'=>'하단영역에 SNS 아이콘 노출(페이스북)',
					'id'=>$theme_shortname.'_sns_facebook_enable',
					'type'=>'radio'),
			array('name'=>'하단영역에 SNS 아이콘 노출(페이스북)',
					'id'=>$theme_shortname.'_sns_facebook_url',
					'type'=>'text'),
			array('name'=>'하단영역에 SNS 아이콘 노출(Google+)',
					'id'=>$theme_shortname.'_sns_google_enable',
					'type'=>'radio'),
			array('name'=>'하단영역에 SNS 아이콘 노출(Google+)',
					'id'=>$theme_shortname.'_sns_google_url',
					'type'=>'text'),
			array("name"=>"카카오 자스 앱키",
					"id"=>$theme_shortname."_sns_share_kakao_js_appkey",
					"type"=>"")
		),

	'map'=>
		array(
			array('name'=>'지도API(찾아오시는길)',
					'type'=>'title'),
			array('name'=>'지도API(찾아오시는길) 숨김설정',
					'id'=>$theme_shortname.'_map_preOpen',
					'type'=>'hidden'),
			array('name'=>'지도 노출시 주소 및 연락처 표시 설정',
					'id'=>$theme_shortname.'_map_addr_info_view',
					'type'=>'text'),
			array('name'=>'주소 (오시는길)',
					'id'=>$theme_shortname.'_map_addr',
					'type'=>'text'),
			array('name'=>'네이버 Client ID',
					'id'=>$theme_shortname.'_map_client_id',
					'type'=>'text'),
			array('name'=>'네이버 Client Secret',
					'id'=>$theme_shortname.'_map_client_secret',
					'type'=>'text'),
			array('name'=>'네이버 이름 (마커 표시용)',
					'id'=>$theme_shortname.'_map_mkr_name',
					'type'=>'text'),
			array('name'=>'네이버 Key',
					'id'=>$theme_shortname.'_map_key',
					'type'=>'text'),
			array('name'=>'네이버 전화번호/팩스/이메일',
					'id'=>$theme_shortname.'_map_infomation',
					'type'=>'text'),
			array("name"=>"카카오 API Key",
					"id"=>$theme_shortname."_map_daum_appkey",
					"type"=>""),
			array("name"=>"다음 Key",
					"id"=>$theme_shortname."_map_daum_key",
					"type"=>""),
			array("name"=>"다음 지도주소",
					"id"=>$theme_shortname."_map_daum_addr",
					"type"=>""),
			array("name"=>"다음 마커 이름",
					"id"=>$theme_shortname."_map_daum_mkr_name",
					"type"=>""),
			array("name"=>"다음 마커 주소",
					"id"=>$theme_shortname."_map_daum_mkr_addr",
					"type"=>""),
			array("name"=>"다음 마커 연락처",
					"id"=>$theme_shortname."_map_daum_mkr_phone",
					"type"=>""),
			array("name"=>"다음 전화번호/팩스/이메일",
					"id"=>$theme_shortname."_map_daum_infomation",
					"type"=>"")
		),

	'seo'=>
		array(
			array('name'=>'SEO',
					'type'=>'title'),
			array('name'=>'SEO 숨김설정',
					'id'=>$theme_shortname.'_seo_preOpen',
					'type'=>'hidden'),
			array('name'=>'SEO 타이틀',
					'id'=>$theme_shortname.'_seo_title',
					'type'=>'textarea'),
			array('name'=>'SEO 설명',
					'id'=>$theme_shortname.'_seo_description',
					'type'=>'textarea'),
			array('name'=>'SEO 키워드',
					'id'=>$theme_shortname.'_seo_keywords',
					'type'=>'textarea'),
			array('name'=>'구조화 데이터',
					'id'=>$theme_shortname.'_structured_type',
					'type'=>'textarea'),
		),

	"naver"=>
		array(
			array("name"=>"NAVER",
					"type"=>"title"),
			array('name'=>'항목열어두기',
					'id'=>$theme_shortname.'_naver_preOpen',
					'type'=>""),
			array("name"=>"네이버 블로그 연동 사용여부",
					"id"=>$theme_shortname."_naver_blog_api_use",
					"type"=>""),
			array("name"=>"웹마스터",
					"id"=>$theme_shortname."_naver_use_webmaster",
					"type"=>""),
			array("name"=>"네이버 블로그 연동 사용여부",
					"id"=>$theme_shortname."_naver_owntag",
					"type"=>""),
			array("name"=>"네이버 블로그 연동 사용여부",
					"id"=>$theme_shortname."_naver_syndiToken",
					"type"=>""),
			array("name"=>"네이버 블로그 API 연결 URL",
					"id"=>$theme_shortname."_naver_blog_api_url",
					"type"=>""),
			array("name"=>"네이버 블로그 API 연결 아이디",
					"id"=>$theme_shortname."_naver_blog_api_id",
					"type"=>""),
			array("name"=>"네이버 블로그 API 연결 암호",
					"id"=>$theme_shortname."_naver_blog_api_pw",
					"type"=>""),
			array("name"=>"네이버 블로그 연결 시 출처 표시 여부",
					"id"=>$theme_shortname."_naver_blog_api_origin",
					"type"=>""),
			array("name"=>"네이버 블로그 카테고리",
					"id"=>$theme_shortname."_naver_blog_api_category",
					"type"=>""),
			array("name"=>"네이버 블로그 카테고리 업데이트 일자",
					"id"=>$theme_shortname."_naver_blog_api_category_update_date",
					"type"=>""),

			array("name"=>"네이버 애널리틱스",
					"id"=>$theme_shortname."_naver_analytics_use",
					"type"=>""),
			array("name"=>"네이버 애널리틱스",
					"id"=>$theme_shortname."_naver_analytics_id",
					"type"=>""),
		),

	"tistory"=>
		array(
			array("name"=>"tistory",
					"type"=>"title"),

      array('name'=>'항목열어두기',
					'id'=>$theme_shortname.'_tistory_preOpen',
					'type'=>""),
			array("name"=>"티스토리",
					"id"=>$theme_shortname."_tistory_use",
					"type"=>""),

			array("name"=>"티스토리",
					"id"=>$theme_shortname."_tistory_url",
					"type"=>""),
			array("name"=>"티스토리",
					"id"=>$theme_shortname."_tistory_callback",
					"type"=>""),
			array("name"=>"티스토리",
					"id"=>$theme_shortname."_tistory_clientid",
					"type"=>""),
			array("name"=>"티스토리",
					"id"=>$theme_shortname."_tistory_skey",
					"type"=>""),
			array("name"=>"티스토리",
					"id"=>$theme_shortname."_tistory_accesstoken",
					"type"=>""),
			array("name"=>"티스토리",
					"id"=>$theme_shortname."_tistory_accesstoken_time",
					"type"=>""),

			array("name"=>"티스토리",
					"id"=>$theme_shortname."_tistory_category",
					"type"=>""),
			array("name"=>"티스토리",
					"id"=>$theme_shortname."_tistory_category_time",
					"type"=>""),
    ),

	"google"=>
		array(
			array("name"=>"google",
					"type"=>"title"),

      array('name'=>'항목열어두기',
					'id'=>$theme_shortname.'_google_preOpen',
					'type'=>""),
			array("name"=>"구글",
					"id"=>$theme_shortname."_google_use_webmaster",
					"type"=>""),
			array("name"=>"구글",
					"id"=>$theme_shortname."_google_use_analytics",
					"type"=>""),
			array("name"=>"구글",
					"id"=>$theme_shortname."_google_use_authorship",
					"type"=>""),

			array("name"=>"구글",
					"id"=>$theme_shortname."_google_owntag",
					"type"=>""),

			array("name"=>"구글",
					"id"=>$theme_shortname."_google_trackingid",
					"type"=>""),

			array("name"=>"구글",
					"id"=>$theme_shortname."_google_option1",
					"type"=>""),
			array("name"=>"구글",
					"id"=>$theme_shortname."_google_option2",
					"type"=>""),
			array("name"=>"구글",
					"id"=>$theme_shortname."_google_option3",
					"type"=>""),
			array("name"=>"구글",
					"id"=>$theme_shortname."_google_plusurl",
					"type"=>""),
    ),

	"bing"=>
		array(
			array("name"=>"bing",
					"type"=>"title"),

      array('name'=>'항목열어두기',
					'id'=>$theme_shortname.'_bing_preOpen',
					'type'=>""),
			array("name"=>"구글",
					"id"=>$theme_shortname."_bing_use_webmaster",
					"type"=>""),
			array("name"=>"구글",
					"id"=>$theme_shortname."_bing_owntag",
					"type"=>""),

    ),
	"baidu"=>
		array(
			array("name"=>"baidu",
					"type"=>"title"),

      array('name'=>'항목열어두기',
					'id'=>$theme_shortname.'_baidu_preOpen',
					'type'=>""),
			array("name"=>"바이두",
					"id"=>$theme_shortname."_baidu_use_webmaster",
					"type"=>""),
			array("name"=>"바이두",
					"id"=>$theme_shortname."_baidu_use_analytics",
					"type"=>""),
			array("name"=>"바이두",
					"id"=>$theme_shortname."_baidu_use_authorship",
					"type"=>""),

			array("name"=>"바이두",
					"id"=>$theme_shortname."_baidu_owntag",
					"type"=>""),

			array("name"=>"바이두",
					"id"=>$theme_shortname."_baidu_trackingid",
					"type"=>""),

			array("name"=>"바이두",
					"id"=>$theme_shortname."_baidu_option1",
					"type"=>""),
			array("name"=>"바이두",
					"id"=>$theme_shortname."_baidu_option2",
					"type"=>""),
			array("name"=>"바이두",
					"id"=>$theme_shortname."_baidu_plusurl",
					"type"=>""),
    ),
	"sitemap"=>
		array(
			array("name"=>"sitemap",
					"type"=>"title"),
      array('name'=>'항목열어두기',
					'id'=>$theme_shortname.'_sitemap_preOpen',
					'type'=>""),
			array("name"=>"사이트맵 파일",
					"id"=>$theme_shortname."_sitemap_usefile",
					"type"=>""),
    ),

);
